"""create features engine_window

Revision ID: e3e436e8bb0c
Revises: f3e7be5076bd
Create Date: 2026-04-25 11:07:22.975898

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e436e8bb0c'
down_revision: str | None = 'f3e7be5076bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS features")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_window',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('training_run_id', sa.String(length=64), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('rul', sa.Integer(), nullable=False),
    sa.Column('parquet_uri', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_run_id', 'engine_id', 'cycle', name='uq_engine_window_run_engine_cycle'),
    schema='features'
    )
    op.create_index(op.f('ix_features_engine_window_training_run_id'), 'engine_window', ['training_run_id'], unique=False, schema='features')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_engine_window_training_run_id'), table_name='engine_window', schema='features')
    op.drop_table('engine_window', schema='features')
    op.execute("DROP SCHEMA IF EXISTS features CASCADE")
    # ### end Alembic commands ###
