"""create raw_sensor readings

Revision ID: f3e7be5076bd
Revises: 
Create Date: 2026-04-23 21:59:52.984203

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e7be5076bd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS raw_sensor")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('op_setting_1', sa.Float(), nullable=False),
    sa.Column('op_setting_2', sa.Float(), nullable=False),
    sa.Column('op_setting_3', sa.Float(), nullable=False),
    sa.Column('sensor_1', sa.Float(), nullable=False),
    sa.Column('sensor_2', sa.Float(), nullable=False),
    sa.Column('sensor_3', sa.Float(), nullable=False),
    sa.Column('sensor_4', sa.Float(), nullable=False),
    sa.Column('sensor_5', sa.Float(), nullable=False),
    sa.Column('sensor_6', sa.Float(), nullable=False),
    sa.Column('sensor_7', sa.Float(), nullable=False),
    sa.Column('sensor_8', sa.Float(), nullable=False),
    sa.Column('sensor_9', sa.Float(), nullable=False),
    sa.Column('sensor_10', sa.Float(), nullable=False),
    sa.Column('sensor_11', sa.Float(), nullable=False),
    sa.Column('sensor_12', sa.Float(), nullable=False),
    sa.Column('sensor_13', sa.Float(), nullable=False),
    sa.Column('sensor_14', sa.Float(), nullable=False),
    sa.Column('sensor_15', sa.Float(), nullable=False),
    sa.Column('sensor_16', sa.Float(), nullable=False),
    sa.Column('sensor_17', sa.Float(), nullable=False),
    sa.Column('sensor_18', sa.Float(), nullable=False),
    sa.Column('sensor_19', sa.Float(), nullable=False),
    sa.Column('sensor_20', sa.Float(), nullable=False),
    sa.Column('sensor_21', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_id', 'cycle', name='uq_readings_engine_cycle'),
    schema='raw_sensor'
    )
    op.create_index(op.f('ix_raw_sensor_readings_engine_id'), 'readings', ['engine_id'], unique=False, schema='raw_sensor')
    op.create_index(op.f('ix_raw_sensor_readings_ts'), 'readings', ['ts'], unique=False, schema='raw_sensor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_sensor_readings_ts'), table_name='readings', schema='raw_sensor')
    op.drop_index(op.f('ix_raw_sensor_readings_engine_id'), table_name='readings', schema='raw_sensor')
    op.drop_table('readings', schema='raw_sensor')
    op.execute("DROP SCHEMA IF EXISTS raw_sensor CASCADE")
    # ### end Alembic commands ###
